version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    assignees:
      - "Neonkraft"
    reviewers:
      - "Neonkraft"
    commit-message:
      prefix: "chore: "
