name: pre-commit

on:

  # Trigger manually
  workflow_dispatch:

  # Trigger on any push to the master
  push:
    branches:
      - main
      - development

  # Trigger on any push to a PR that targets master
  pull_request:
    branches:
      - main
      - development

jobs:

  run-all-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
